
name: Build Flow

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
env:
  VERSION: "0.0.1-SNAPSHOT"
  USERNAME: ${{ secrets.OSSRH_USERNAME }}
  TOKEN: ${{ secrets.OSSRH_TOKEN }}
  ORDER_URL: http://localhost:8085
  KAFKA_SERVER: localhost:9092
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: gradle clean build
